<?php
/*
Template Name: Privacy Policy
*/
?>


<?php
get_header(); // Chama o cabeçalho do tema

?>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="css/style.css">
  <meta name="author" content="Flavia Sigoli"/>
  <meta http-equiv="content-language" content="en-US" />
  <meta http-equiv="content-type" content="html; charset=UTF-8" />
  <meta name="robots" content="index, follow">
  <style type="text/css">
    .privacycontainer h3, h2, h6, cite{
      color: royalblue;
    }
    .privacycontainer {
      color: #000;
     width: 100%;
     max-width: 1200px;
     margin: auto;
      padding: 100px 50px;
      display: flex;
      gap: 20px;
      flex-direction: column;
    }
    .privacycontainer ul{
      padding-left: 25px;
    }
    .privacycontainer p{
    white-space: wrap;
    }
    .p-m-l{
      padding-left: 20px;
    }
    main {
      font-family: Arial, sans-serif;
      margin: 20px;
    }
    .privacycontainer p {
      line-height: 1.6;
      margin-bottom: 15px;
    }
    .privacycontainer p.p-m-l {
      margin-left: 20px;
    }
    .privacycontainer span {
      font-weight: bold;
    }
    @media screen and (max-width:700px) {
       .privacycontainer {
         padding: 100px 10px;
       }
    }
  </style>
</head>
<div class="privacycontainer">
<h1>Privacy Policy</h1>
  <p>Last updated: November 11, 2024
  </p>
  <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
  <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.</p>
  
  <h2>Interpretation and Definitions</h2>
  
  <h3>Interpretation</h3>
  <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
  
  <h3>Definitions</h3>
  <p>For the purposes of this Privacy Policy:</p>
  <ul>
      <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
      <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
      <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to  Oliver´s Cleaning, Columbus, OH.</li>
      <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
      <li><strong>Country</strong> refers to: United States</li>
      <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
      <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
      <li><strong>Service</strong> refers to the Website.</li>
      <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
      <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
      <li><strong>Website</strong> refers to Oliver´s Cleaning, accessible from https://oliverscleaning.com/ </li>
      <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
  </ul>
  
  <h2>Collecting and Using Your Personal Data</h2>
  
  <h3>Types of Data Collected</h3>
  
  <h4>Personal Data</h4>
  <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
  <ul>
      <li>Email address</li>
      <li>First name and last name</li>
      <li>Phone number</li>
      <li>Usage Data</li>
  </ul>
  
  <h4>Usage Data</h4>
  <p>Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
  <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
  
  <h3>Tracking Technologies and Cookies</h3>
  <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
  
  <ul>
      <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
      <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
  </ul>
  
  <h3>Cookies Types</h3>
  <p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. We use both Session and Persistent Cookies for the purposes set out below:</p>
  
  <h4>Necessary / Essential Cookies</h4>
  <ul>
      <li>Type: Session Cookies</li>
      <li>Administered by: Us</li>
      <li>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</li>
  </ul>
  
  <h4>Cookies Policy / Notice Acceptance Cookies</h4>
  <ul>
      <li>Type: Persistent Cookies</li>
      <li>Administered by: Us</li>
      <li>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</li>
  </ul>
  
  <h4>Functionality Cookies</h4>
  <ul>
      <li>Type: Persistent Cookies</li>
      <li>Administered by: Us</li>
      <li>Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</li>
  </ul>
  
  <h2>Use of Your Personal Data</h2>
  <p>The Company may use Personal Data for the following purposes:</p>
  <ul>
      <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
      <li>To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
      <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
      <li>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
  </ul>
  
  <h2>Retention of Your Personal Data</h2>
  <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
  
  <h2>Transfer of Your Personal Data</h2>
  <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
  
  <h2>Delete Your Personal Data</h2>
  <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>
  
  <h2>Disclosure of Your Personal Data</h2>
  <p>We may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
  <ul>
      <li>Comply with a legal obligation</li>
      <li>Protect and defend the rights or property of the Company</li>
      <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
      <li>Protect the personal safety of Users of the Service or the public</li>
      <li>Protect against legal liability</li>
  </ul>
  
  <h2>Security of Your Personal Data</h2>
  <p>The security of Your Personal Data is important to Us. However, please remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
  <h2>Detailed Information on the Processing of Your Personal Data</h2>
  <p>The Service Providers We use may have access to Your Personal Data. These third-party vendors collect, store, use, process and transfer information about Your activity on Our Service in accordance with their Privacy Policies.</p>
  <h6>Usage, Performance and Miscellaneous</h6>
  <p>We may use third-party Service Providers to maintain and improve our Service.</p>
  <p class="p-m-l">
  <h4>Google Places</h4>
  Google Places is a service that returns information about places using HTTP requests. It is operated by Google <br>
  Google Places service may collect information from You and from Your Device for security purposes. <br>
  The information gathered by Google Places is held in accordance with the Privacy Policy of Google: https://www.google.com/intl/en/policies/privacy/
  </p>
  <h2>Children's Privacy</h2>
  Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers. <br>
  If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.
  <h2>Links to Other Websites</h2>
  Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit. <br>
  We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
  <h2>Changes to this Privacy Policy</h2>
  We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
  We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
  You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.

  <h2>Contact Us</h2>
  <p>If you have any questions about this Cookies Policy, You can contact us:</p>
  <ul>
      <li>By email: <a href="mailto:oliverscleaningoh@gmail.com">oliverscleaningoh@gmail.com</a></li>
      <li>By visiting this page on our website: <a href="https://www.oliverscleaning.com/">https://www.oliverscleaning.com/</a></li>
      <li>By phone number: (380) 223-4888</li>
  </ul>
</div>

<?php get_footer(); // Chama o rodapé do tema ?>